trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - '*.*.*'

stages:
  - stage: BuildAndRunOnAzure
    displayName: "Building on Azure"
    jobs:
      - job: RunOn
        displayName: "on Azure workers"
        strategy:
          matrix:
            linux-jdk17:
              imageName: 'ubuntu-latest'
              poolName: "Azure Pipelines"
              os: Linux
              jdk: "1.17"
            windows:
              imageName: "windows-latest"
              poolName: "Azure Pipelines"
              os: macOS
              jdk: "1.17"
        pool:
          vmImage: $(imageName)
          name: $(poolName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - task: Maven@3
            displayName: "Building QuestDB"
            inputs:
              mavenPomFile: "core/pom.xml"
              goals: "package"
              options:
                "-DskipTests -Dhttp.keepAlive=false -P build-web-console,build-binaries"
              jdkVersionOption: $(jdk)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(build.sourcesDirectory)/core/target'
              Contents: '$(build.sourcesDirectory)/core/target/questdb-*.gz'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: SignArtifacts
    displayName: "Sign Artifacts"
    dependsOn:
      - BuildAndRunOnAzure
    jobs:
      - job: Sign
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
              cleanDestinationFolder: true
          - script: |
              find . -type f -exec bash -c 'sha256sum "$0" > "../$0.sha256.txt"' {} \;
              cd ..
              rm -r drop
            workingDirectory: '$(System.ArtifactsDirectory)/drop'
            displayName: "SHA256 checksum"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Release
    displayName: "Release binaries to github"
    dependsOn:
      - SignArtifacts
    jobs:
      - job: Github release
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none
            displayName: "Download binaries"
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Build.ArtifactStagingDirectory)'
              cleanDestinationFolder: true

          - script: |
              echo "Checking if release already exists..."
              release_info=$(curl -H \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$(Build.Repository.Name)/releases/tags/$(Build.SourceVersion)" || true)
              
              if echo "$release_info" | grep -q 'Not Found'; then
                echo "Release does not exist."
                echo "##vso[task.setvariable variable=releaseExists;isOutput=true]false"
              else
                echo "Release already exists."
                echo "##vso[task.setvariable variable=releaseExists;isOutput=true]true"
              fi

          - task: GitHubRelease@1
            displayName: "Upload binaries to release"
            condition: eq(variables['releaseExists'], 'true')
            inputs:
              gitHubConnection: 'ideoma'  # Replace with your GitHub service connection
              repositoryName: 'questdb/questdb'  # e.g., my-org/my-repo
              action: 'edit'
              assets: '$(Build.ArtifactStagingDirectory)/*'

          - task: GitHubRelease@1
            displayName: "Create release"
            condition: eq(variables['releaseExists'], 'false')
            inputs:
              gitHubConnection: 'ideoma'
              repositoryName: 'questdb/questdb'
              target: '$(Build.SourceVersion)'
              action: 'create'
              tagSource: 'gitTag'
              tag: '$(Build.SourceVersion)'
              releaseTitle: 'Release $(Build.SourceVersion)'
              assets: '$(Build.ArtifactStagingDirectory)/*'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
              isDraft: true
